DISCORD_API_BOT_TOKEN = "OTAwMjMwODA5NTE1MDczNTQ2.GU0nfD.aANTA5g5PI1pYqN-I9Zu1r5E5kT0ubuQKJ2A7s"
PORT_NUMBER = 8888  # Port to run the app from

TEXT_COLOR = 0x7A1CFF

YES_REACT = "✅"
NO_REACT = "❌"
DECISION_REACTS = set((YES_REACT, NO_REACT))

PRIVY_DB = "databases/privy_db.sqlite"
TIPS_DIRECTORY = "tips.txt"

HISTORY_LIMIT = 1000
DELETE_DELAY = 0.5
