DISCORD_API_BOT_TOKEN = ""
PORT_NUMBER = 8888  # Port to run the app from

TEXT_COLOR = 0x7A1CFF

YES_REACT = "✅"
NO_REACT = "❌"
DECISION_REACTS = set((YES_REACT, NO_REACT))

TIPS_DIRECTORY = "tips.txt"
